### ISSUE TITLE
Spent all my diamond on Clan Quest ! ! !

### ISSUE THREAD

**Issue by boudboa** [Tune389/Tap-Titans-2-Progress-Bot#12]
That was some good improvement, awesome thanks !

I juste really hate you now.

**Comment by Tune389** [comment]
that happens only if you set clanQuestRunsPerReady up higher then 1 and your not in an top level clan (boss is longer then 1 hour up)

**Comment by boudboa** [comment]
clanQuestRunsPerReady haven't been changed it's sitting at 1. 
It's only doing that since your latest modification of clan quest handling, 
I just set clanQuestRunsPerReady  to zero and it seems to be ok without it.

**Comment by Tune389** [comment]
Okay got it, was a fade Screen problem. Added a color check should work now.

**Comment by PythoniCode** [comment]
In order to not spend extra diamonds you should only attack multiple times once until the boss is dead. Then reset the variables.

**Comment by PythoniCode** [comment]
I've also thrown away 800 diamonds on testing, but it was worth it IMO
