### ISSUE TITLE
Skills doesn't level when stopMasterAfterSkillsUnlocked is 1

### ISSUE THREAD

**Issue by boudboa** [Tune389/Tap-Titans-2-Progress-Bot#19]
I believe it's because you close the menu at the end of :LevelHeroes but only reopen it in :LevelUp
I added a few toasts in :checkskill and could see those printing but the menu was actually closed...

**Comment by Tune389** [comment]
This option only works with justUnlockSkills 1 at the current state. Because it makes no sense to level up all the skills and not the ms.

**Comment by justnoob93** [comment]
thank you ..is working fine
