### ISSUE TITLE
v1.3 dev 1 - Prestige too early

### ISSUE THREAD

**Issue by galipop** [Tune389/Tap-Titans-2-Progress-Bot#21]
Never noticed this issue in earlier releases, but I was watching the bot this morning and he prestiged just after 58 mins. After the prestige the timer was still at 58 mins.

#showCurrentTime 1
#enableAutoprestige 1
#prestigeAfterXMinutes 60

I have CQ enabled in 1.3, which I never had enabled before, so that may be having an impact. I will disable CQ when I get home from work today and see if the bot still prestige's early.

**Comment by galipop** [comment]
Ok, I've adjusted prestigeAfterXMinutes a few times and prestige always seems to happen a few minutes early according to the timer. For now I just set to target number of minutes + 3.

Cheers

**Comment by PythoniCode** [comment]
I think it doesn't always keep track of the time

**Comment by galipop** [comment]
It's no big deal. Maybe the display of the time is not in sync with the actual time in hiro.
