### ISSUE TITLE
Hatching Egg and Clan Quest

### ISSUE THREAD

**Issue by Osakawa** [Tune389/Tap-Titans-2-Progress-Bot#22]
hello, sometimes it doesnt hatch the eggs and doesnt go to the clan quests, also sometimes it doesnt do prestige. i think all of them started happening after the game had update.

**Comment by galipop** [comment]
v1.3 I haven't had an issue with egg hatching.

I do have issue with CQ though. ABout half the time the bot ignore CQ icon. I usually have to restart the script.

**Comment by rake146** [comment]
galipop, what are your settings for the WC and SC so you can get them back to back forever? I am having trouble timing them, each lasts for 90 seconds and then they have to cooldown, any ideas?

**Comment by galipop** [comment]
I only use WC.  Interval is set to 5 secs.

**Comment by rake146** [comment]
Oh right thanks, is there any way to upgrade an ability by a few levels, there seems to only be an option for either all of them to max or just 1 point.
