### ISSUE TITLE
Hero levelling

### ISSUE THREAD

**Issue by rake146** [Tune389/Tap-Titans-2-Progress-Bot#23]
Hey, would there be any possibility that it could stop levelling heroes over 4000?

**Comment by Tune389** [comment]
No way with HiroMacro, to much color checks. But we can limit the scrolls (to top) and level only the last 10-15 Heroes.

**Comment by rake146** [comment]
Oh right, you need to passive I guess though from the earlier ones, is there a possibility that we can upgrade the skills a couple of points rather than either 1 or maxed?

**Comment by galipop** [comment]
On the topic of skill upgrades for the master....

Maybe implement an option similar to #skillIntensity which will click on the master's skills based on the value of intensity.

#skillMasterIntensity 3 will click on the skills 3 times each.
