### ISSUE TITLE
Menu opening then closing

### ISSUE THREAD

**Issue by rake146** [Tune389/Tap-Titans-2-Progress-Bot#24]
Anyone have issues with the menu opening and then closing instantly, not upgrading any heroes?

**Comment by billylee5354** [comment]
I have the same problem. just opening and closing the menu, nothing else.

**Comment by justnoob93** [comment]
1stly check your hiro macro (HiroMacro Settings -> Color Access Method -> ScreenCapture )
2nd Set ScreenCapture delay in HiroMakro settings to 0
3rd languages must be English on your games setting.
