### ISSUE TITLE
Auto-Prestige

### ISSUE THREAD

**Issue by Fockeroo** [Tune389/Tap-Titans-2-Progress-Bot#26]
I can't seem to get the auto prestige to work. Doesn't matter what I put at
var #enableAutoprestige x
var #prestigeAfterXMinutes x

I just cant get it to work. Send halp.

**Comment by PatrickN2282** [comment]
#enableAutoprestige 1 (1 for enable, or 0 for disable)
#prestigeafterxminutes 40 (after 40 minutes you will prestige)

you need to be at least lvl 600 with you swordmaster for the possibility to prestige

**Comment by PythoniCode** [comment]
Checking what stage you are in is nearly impossible to do reliably.
