### ISSUE TITLE
Random Click Points for Flash Zip and Clan-Ship

### ISSUE THREAD

**Issue by PatrickN2282** [Tune389/Tap-Titans-2-Progress-Bot#27]
Hi there,
would it be possible to direct the Random Clicks to the points for Flash zip? Would kill Bosses much faster!

**Comment by justnoob93** [comment]
Boss can;t use zip !

**Comment by galipop** [comment]
Not really possible with Hiromacro. Hiromacro API only can read color at a pixel location.
