### ISSUE TITLE
Clicks slowly

### ISSUE THREAD

**Issue by czzz223** [Tune389/Tap-Titans-2-Progress-Bot#28]
I've followed instructions properly but the bot only clicks 1-2 times per 3-5 seconds. Clicks are appearing on the far left side of the screen.

**Comment by jspaeter** [comment]
Same problem for me :/

**Comment by galipop** [comment]
Which emulator do you use?

I had this issue in bluestacks. I now use memu and don't have this issue.

**Comment by jspaeter** [comment]
I'm using Nox with the lastest update of TT2 :/

**Comment by jspaeter** [comment]
Up?

**Comment by jayrc** [comment]
I had that issue when I first started using it, try doing a direct copy, and make sure the HiroMacro preferences are set properly.... Once I used the default settings it sorted itself out. - so I was more careful about my editing in the future, which has managed to leave it working.
