### ISSUE TITLE
Popup windows after prestiging

### ISSUE THREAD

**Issue by Xilous** [Tune389/Tap-Titans-2-Progress-Bot#29]
The game is now doing popups for diamond rewards or other rewards after you prestige. This means the bot can't go on until this window goes away by clicking the 'collect' button. 

Can the bot maybe start doing some clicks on the coordinates of where this window appears from time to time?

**Comment by galipop** [comment]
Sometimes the game crashes on prestige, and this resets all your settings to default - specifically fairy ads are enabled.

I don't think the crashing is caused by the bot, but by bad coding in the game client.
