### ISSUE TITLE
About clan quest

### ISSUE THREAD

**Issue by justnoob93** [Tune389/Tap-Titans-2-Progress-Bot#3]
if i enable it Clan quest it keep attack the titans.. and keep using the diamond to hit...can it hit 1 time or use max 5 diamond to hit..?

**Comment by Tune389** [comment]
Yes thats on my todo list. You can update your Script to the current "git" version. I Fixed some bugs.

**Comment by justnoob93** [comment]
and i found out 2 more error . 
1st. is the skill try to up 1 lvl . but i seen only 1st 3 skill been click ..other nope
2nd. when stuck on the boss, wouldn't continues to try to hit the boss..

**Comment by Tune389** [comment]
1nd: the "problem" is the fade screen between the stages, but I dont't see that as a problem. You still fight so fast, you cant be faster with that last 2-3 skills. And later the bot will get these missing skills.
2nd: set this to zero: `#startBossSkill 4`

**Comment by justnoob93** [comment]
Hi, been test running 24hour ..working well ..1 and 2 problem is solve ! . Only the clan is not working ..is ok ..still can manual to hit it

**Comment by justnoob93** [comment]
Hi

IF i set this to zero: #startBossSkill 4 , will auto continues if fail.but after maybe 20-40 min it won;t run (#runActionsEveryXMinutes 3) . is mean keep taping without click hero.

**Comment by Tune389** [comment]
Clan Quest should work now in v1.1. Can't reproduce your other problem, Scripts runs stable after a 8h run tonight.
