### ISSUE TITLE
"No Thanks" to Fairy Ad

### ISSUE THREAD

**Issue by OthorWight** [Tune389/Tap-Titans-2-Progress-Bot#32]
Click the "No Thanks" button when a fairy ad screen comes up.
You can add this code to the RANDOM ATTACK section in between the "Equipment Stacking" and the Touch.

       var #noThanksColor 0
       getColor #noThanksColor 134 620
       if #noThanksColor == 688378
              touchDown 0 134 620
              sleep #btnDelay
              #time = #time + #btnDelay
              touchUp 0
              sleep #btnDelay
              #time = #time + #btnDelay
       endif

**Comment by talfirevic** [comment]
adding this slows down tapping, so I'm assuming this is getting triggered even if it's not on fairy ad.

**Comment by OthorWight** [comment]
I haven't noticed any slowdowns while using this, but I have been making a lot of changes. 
https://github.com/OthorWight/Tap-Titans-2-Progress-Bot/blob/experimental/TapTitans2AdvancedClickBot.txt
