### ISSUE TITLE
Slower "Random Tapping"

### ISSUE THREAD

**Issue by 88Ldh** [Tune389/Tap-Titans-2-Progress-Bot#33]
If i have this option ( Random Taping) enabled, is there a way to make it a bit slower? like to half of the original speed?

**Comment by Tune389** [comment]
Just increase or double the #hitDelay count (40: default)

**Comment by jayrc** [comment]
Hi Tune389,

When I do that, my skills activate much slower... is there another setting where I can lessen the number of taps in the cycle?

Thank you!
