### ISSUE TITLE
Some issues I've found

### ISSUE THREAD

**Issue by dranrebn** [Tune389/Tap-Titans-2-Progress-Bot#34]
-Level Heroes need re-work after v2.1.1 (not tapping all heroes)
-Level MS/Prestige also need re-work after v2.1.1 (not unlocking all skills)
-Last hero to be fixed with Fin as first hero, Nohni on second, and Damon on third

More power to you and thanks for all your work!

**Comment by dranrebn** [comment]
3rd one has been fixed. Thanks!

About the other two. I think there are changes in the layout of Heroes in TT v2. Now when you level heroes, I cannot level Damon and sometimes skipped other heroes.

Same with MS level and skills. I think the layout was changed and auto prestige will not work.

**Comment by Tune389** [comment]
can you send me a screen? I can't reproduce this problems with v2.

**Comment by howellhou** [comment]
Yes, the same for me.. It's not unlocking and upgrading skills(but sometimes it works).

**Comment by howellhou** [comment]
It's also not clicking clan ship even if I set it to 1. Can you kindly fix it?

**Comment by dranrebn** [comment]
I've fixed mine. I cannot access my superuser that's why I have to reset Nox. Also, need to make sure 2 cores are active with 2GB or more memory.
