### ISSUE TITLE
suggestion for update

### ISSUE THREAD

**Issue by Hantuhantuhantu** [Tune389/Tap-Titans-2-Progress-Bot#45]
set non main hero max upgrade level 6K to just unlock all skills

**Comment by jayrc** [comment]
Trying to have the script determine the level of heroes is very difficult, if not impossible with the way the script reads the screen. Especially with variations like not actually going down to the bottom of the heroes list... it has no idea where it actually is, it just pushes enough to be where it SHOULD be, not necessarily where it is supposed to be. I hope this makes sense.

Shortened: The script looks at individual pixels for specific colors to know to do what it is supposed to do, coding to check for a specific # is not going to work.

**Comment by jayrc** [comment]
But Good News! With the update coming Wednesday this week, the heroes will self cap at 6k, and now we will have a new ascension mechanic for them, and they may be reordered, so the script will have to be updated.

**Comment by jayrc** [comment]
Please review the latest release, it addresses your concern, and the patch made this a non-issue. Please close when you get a chance.
