### ISSUE TITLE
Leveling-up skills

### ISSUE THREAD

**Issue by 88Ldh** [Tune389/Tap-Titans-2-Progress-Bot#46]
when you set the script to "just unlock skills", how can i make it hit each skill 5 times instead of just once?

**Comment by jayrc** [comment]
Just unlock means it only hits them the one time.

Your best way around it is to set the check now to 0 and manually adjusting the skills, unless you leave it and it auto prestiges and then those runs will only get the 1x

**Comment by jayrc** [comment]
I think this will do it...

Find:

:checkSkillsUnlock
	
	sleep 200
	#time = #time + 250
	
	getRGB #colorRed #colorGreen #colorBlue 450 710
	
	if #colorBlue == 2 or #colorBlue == 5
		#skillsUnlocked = #skillsUnlocked + 1
	endif
	
	if #colorBlue == 2
		sleep 100
		touchDown 0 466 730
		sleep 250
		touchUp 0
		sleep 200
		#time = #time + 450
	endif

And duplicate the last bit... I cannot test at the moment, but it should do it for you.

:checkSkillsUnlock
	
	sleep 200
	#time = #time + 250
	
	getRGB #colorRed #colorGreen #colorBlue 450 710
	
	if #colorBlue == 2 or #colorBlue == 5
		#skillsUnlocked = #skillsUnlocked + 1
	endif
	
	if #colorBlue == 2
		sleep 100
		touchDown 0 466 730
		sleep 250
		touchUp 0
		sleep 200
		#time = #time + 450
		sleep 100
		touchDown 0 466 730
		sleep 250
		touchUp 0
		sleep 200
		#time = #time + 450
		sleep 100
		touchDown 0 466 730
		sleep 250
		touchUp 0
		sleep 200
		#time = #time + 450
		sleep 100
		touchDown 0 466 730
		sleep 250
		touchUp 0
		sleep 200
		#time = #time + 450
		sleep 100
		touchDown 0 466 730
		sleep 250
		touchUp 0
		sleep 200
		#time = #time + 450
	endif

That /SHOULD/ do 5 hits, again I have not tested, but you can run with it.

**Comment by 88Ldh** [comment]
@jayrc it works! thank you.

**Comment by jayrc** [comment]
Very welcome, please close this as it is now resolved :P
