### ISSUE TITLE
New version 2.4.0

### ISSUE THREAD

**Issue by Sanchoys** [Tune389/Tap-Titans-2-Progress-Bot#48]
In the new version of the game the characters go in the reverse order. How can I fix it?

**Comment by jayrc** [comment]
Look at the way that the skills level up and apply that logic to the part where it is going over the heroes... that is the easy way, I will be playing with it after the tourney

**Comment by jayrc** [comment]
This has been updated with the latest release. - You can close this request.

**Comment by jayrc** [comment]
Although after testing it, you may want to increase the frequency with which you check your heroes, I have mine set to 6 minutes, instead of the default 3, putting it back will get more consistent results.
