### ISSUE TITLE
Not upgrading Top hero.

### ISSUE THREAD

**Issue by MathieuB27** [Tune389/Tap-Titans-2-Progress-Bot#50]
Awesome work. This is amazing.
I have a small issue. 
When the script upgrade Hero it most of the time do not upgrade the best hero and 3rd.
I don't know why.

**Comment by MathieuB27** [comment]
I look all over the code I don't see where When Upgrading the Hero It slide back to the top and I don't know why slide juste a little down. The thing is because of this small slide down It always upgrade the 2nd top here. Not the 1st.

**Comment by MathieuB27** [comment]
I finaly Figure that it can be so easily fix with : 
var #maxOutHero 1

My Bad
Great Work

**Comment by eljano** [comment]
where did you put your fix
