### ISSUE TITLE
#shipDelay is not define so ClanShip is not working

### ISSUE THREAD

**Issue by MathieuB27** [Tune389/Tap-Titans-2-Progress-Bot#51]
I have a 1 at #enableClanShip
But it never tap on the ship
I  check in the code and nowhere the #shipDelay is defined.
Is it normal or a but.
If so can you help on that.

**Comment by MathieuB27** [comment]
I found that the issue is where it tap and maybe when
I move the code where you toast the time and change the position to 80 105
I thinks it will not interfere with tournament and it trigger the Ship

**Comment by Tune389** [comment]
Fixed in 1.5 dev 4

**Comment by MathieuB27** [comment]
Great Thanks.
Do you know when you will release this version.
I fix mine myself
