### ISSUE TITLE
2.7.0 update and Nox 5.1 Android issue with the scripts

### ISSUE THREAD

**Issue by atereshkov** [Tune389/Tap-Titans-2-Progress-Bot#75]
With the new update v 2.7.0 Android <5 (4.4.2 as well) will no longer be supported.
So I've ran Nox with Android 5.1 and it seems that script is not working with the same setup (and ofc 480x800 dimension). 
I have no idea how to fix it.
I noticed that the real size of Nox Android 5.1 simulator is bigger than previous Nox 4.4.2 simulator, but in the settings the dimension still the same.

Any suggestions?

**Comment by Speiky55** [comment]
why your nox is so old? i have nox on 6.0.3.0 ;D try to update this first i dont have the new updated yet but i think it should still work

**Comment by atereshkov** [comment]
@Speiky55 you're talking about Nox version, but not Android version.
Your Nox version can be 6.0.x.... whatever, but they're going to upgrade Android minimum supported version to 5.0. 
Nox has 5.1 Android simulator, but look at the first comment of this issue to see the problem.
Do you see the problem now?

**Comment by Speiky55** [comment]
where can i check my nox version ?
i think there will be a oportunity to use nox i mean how many youtubers use nox to play tt2

**Comment by Zethu5** [comment]
Yeah... I expirience the issue as well...
I start the script, and it clicks like 1-2 times and then stops.

If anyone has a  solution I will be gratefull.

**Comment by jayrc** [comment]
The init code I had in place (cloned from someone else) runs, but the transitions is what it is having issues with. (Goto :place) then executing code from there.

**Comment by atereshkov** [comment]
@jayrc damn it

**Comment by snapclick** [comment]
same... not working

**Comment by Speiky55** [comment]
so how can we fix it or are you already working for a new one?

**Comment by jayrc** [comment]
Quick Google searches are not showing the issue or solution, and I am an amateur for sure... I hope it is being worked on by people much smarter than myself.

**Comment by MathieuB27** [comment]
Nothing Work on my side to. I will review all of the code tonight and try to find the answer. If anyone have clue or idea post everything here. I will be back in 3 hours to start debug

**Comment by jayrc** [comment]
#77 - Comment out the CheckApp and following if to endif, in both instances, one in the Init area, and one in the Check Skills, will get the code working... but means that it will execute the commands regardless of the app running or not.

//	CheckApp #checkRunning com.gamehivecorp.taptitans2
//	if #checkRunning == 0
//		RunApp com.gamehivecorp.taptitans2
//		WaitApp com.gamehivecorp.taptitans2
//		sleep 10000
//	endif

**Comment by DonDende** [comment]
Commenting those out makes the bot do things but now it acts like a retard, it's just unusable until it is fixed properly.

**Comment by DonDende** [comment]
nvm that, thank you good sir for your time a dedication for that lovley fix.
