### ISSUE TITLE
Pet Heart of Midas - PHoM

### ISSUE THREAD

**Issue by GitGud2018** [Tune389/Tap-Titans-2-Progress-Bot#84]
thanks @chrisreyn for the update
it seems to be working great, so far I haven't seen any problems, yet
I do have a suggestion, though
since cs phom is currently meta and I don't use HS right now, I made a little change to the script, so it taps on the pet instead of HS, when the HS timer is up
but it would probably be better to just add it like enableclanship, so people can easily turn phom clicking on or off

in the // ---------- Click Areas

var #enablePHoM 1
//will click on pet to collect Pet Heart of Midas Gold

in ":pressSkills" directly under the enableclanship code:

if #enablePHoM == 1
		touchPress 0 280 380
		sleep #btnDelay
		touchPress 0 280 380
		sleep #btnDelay
		#time = #time + 2 * #btnDelay		
endif

actually you don't even need the extra tap, because pet is not a button and you don't need extra delays and taps for it, so honestly, you could just make it 1 touchPress and be done, that's up to you

**Comment by atereshkov** [comment]
Great!

**Comment by Plarium1** [comment]
@GitGud2018 can you share your script pls?
