### ISSUE TITLE
Can't seem to get #startBossSkill to work

### ISSUE THREAD

**Issue by Norenzo** [Tune389/Tap-Titans-2-Progress-Bot#89]
When you fail a boss fight, I want the bot to start fight boss again with  #startBossSkill. But can't seem to get it working, anyone running into trouble with this or is able to help? any help is much greatly appreciated. Thank you.

**Comment by Vhivi** [comment]
Yes the problem has been solved and should be in the next version. #86 

Here is the piece of code replaced : 
`:pressSkills
	//click "Fight Boss"
	getColor #color 372 24
	if #color == 1076975
		toast FightBoss1
		touchPress 0 390 36
		sleep #btnDelay
		#time = #time + #btnDelay
	endif`

**Comment by DaBest1Evar** [comment]
@Vhivi it works wonderfully, thanks!! Turns out I placed my piece of code in the wrong section, it took me a bit to figure out, thanks for your help!!

**Comment by Norenzo** [comment]
@Vhivi Thanks so much, got it working. 👍
